name: model
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Adjusting SDK version for better compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.0
  http: ^1.2.1
  image_picker: ^1.1.2
  webview_flutter: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Downgrading flutter_lints for compatibility

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"
  min_sdk_android: 21
