name: model
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: '>=2.19.5 <3.0.0'

=======
  sdk: ">=2.17.0 <4.0.0" # Adjusting SDK version for better compatibility
>>>>>>> cd02eb51d47f79df99287910edf535c79e49bd29

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
<<<<<<< HEAD
  flutter_launcher_icons: ^0.14.1
=======
  flutter_launcher_icons: ^0.14.0
>>>>>>> cd02eb51d47f79df99287910edf535c79e49bd29
  http: ^1.2.1
  image_picker: ^1.1.2
  webview_flutter: ^4.0.0







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Downgrading flutter_lints for compatibility

<<<<<<< HEAD

  flutter_lints: ^3.0.0


flutter:

=======
flutter:
>>>>>>> cd02eb51d47f79df99287910edf535c79e49bd29
  uses-material-design: true
  assets:
    - images/
    - images/app_icon.png

<<<<<<< HEAD

  # fonts:
  #   - family: Cera Pro
  #     fonts:
  #       - asset: assets/fonts/Cera-Pro-Bold.otf
  #       - asset: assets/fonts/Cera-Pro-Medium.otf
  # #   - family: Trajan Pro
  # #     fonts:
  # #       - asset: fonts/TrajanPro.ttf
  # #       - asset: fonts/TrajanPro_Bold.ttf
  # #         weight: 700
  # #
  # # For details regarding fonts from package dependencies,
  # # see https://flutter.dev/custom-fonts/#from-packages

=======
>>>>>>> cd02eb51d47f79df99287910edf535c79e49bd29
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"
<<<<<<< HEAD
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/app_icon.png"
=======
  min_sdk_android: 21
>>>>>>> cd02eb51d47f79df99287910edf535c79e49bd29
